repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: swift-format-lint
        name: swift-format lint
        entry: xcrun swift-format lint --configuration .swift-format --strict
        language: system
        types: [swift]

      - id: swiftlint
        name: SwiftLint
        entry: swiftlint lint --quiet --force-exclude
        language: system
        types: [swift]
