import Foundation

/// Compares backend date-only plan anchors with dates selected in the user's calendar.
///
/// Plan dates arrive as UTC-midnight instants for a backend `YYYY-MM-DD` value. A selected
/// date is an instant generated by the device calendar. Comparing those instants in only one
/// time zone can move one side across midnight, so calendar-day identity compares their
/// respective year/month/day components instead.
enum PlanCalendarDayIdentity {
  private struct Components: Equatable, Sendable {
    let year: Int
    let month: Int
    let day: Int

    var dateComponents: DateComponents {
      DateComponents(year: year, month: month, day: day)
    }
  }

  static func matches(
    planDate: Date,
    selectedDate: Date,
    selectedCalendar: Calendar
  ) -> Bool {
    components(of: planDate, in: utcCalendar)
      == components(of: selectedDate, in: selectedCalendar)
  }

  static func dayOffset(
    fromPlanDate planDate: Date,
    toSelectedDate selectedDate: Date,
    selectedCalendar: Calendar
  ) -> Int? {
    let calendar = utcCalendar
    guard
      let planComponents = components(of: planDate, in: calendar),
      let selectedComponents = components(of: selectedDate, in: selectedCalendar),
      let planDay = calendar.date(from: planComponents.dateComponents),
      let selectedDay = calendar.date(from: selectedComponents.dateComponents)
    else {
      return nil
    }
    return calendar.dateComponents([.day], from: planDay, to: selectedDay).day
  }

  static func isSameUTCDate(_ lhs: Date, _ rhs: Date) -> Bool {
    utcCalendar.isDate(lhs, inSameDayAs: rhs)
  }

  private static func components(of date: Date, in calendar: Calendar) -> Components? {
    let components = calendar.dateComponents([.year, .month, .day], from: date)
    guard
      let year = components.year,
      let month = components.month,
      let day = components.day
    else {
      return nil
    }
    return Components(year: year, month: month, day: day)
  }

  static var utcCalendar: Calendar {
    var calendar = Calendar(identifier: .gregorian)
    calendar.timeZone = utcTimeZone
    return calendar
  }

  static var utcTimeZone: TimeZone {
    TimeZone(secondsFromGMT: 0) ?? TimeZone.current
  }
}
