import Foundation

enum ChatStrings {
  static let messages = localized("chat.messages")
  static let noConversations = localized("chat.noConversations")
  static let image = localized("chat.image")
  static let imageUnavailable = localized("chat.imageUnavailable")
  static let sending = localized("chat.sending")
  static let sendFailed = localized("chat.sendFailed")
  static let retry = localized("chat.retry")
  static let delivered = localized("chat.delivered")
  static let read = localized("chat.read")
  static let composerPlaceholder = localized("chat.composerPlaceholder")
  static let send = localized("chat.send")
  static let choosePhoto = localized("chat.choosePhoto")
  static let close = localized("chat.close")
  static let closePlayback = localized("chat.closePlayback")
  static let closeAnnotation = localized("chat.closeAnnotation")
  static let loadOlder = localized("chat.loadOlder")
  static let preparingImage = localized("chat.preparingImage")
  static let imagePreparationFailed = localized("chat.imagePreparationFailed")
  static let unread = localized("chat.unread")
  static let trainingShare = localized("chat.trainingShare")
  static let setNumber = localized("chat.setNumber")
  static let load = localized("chat.load")
  static let playVideo = localized("chat.playVideo")
  static let playPlayback = localized("chat.playPlayback")
  static let pausePlayback = localized("chat.pausePlayback")
  static let videoPlayback = localized("chat.videoPlayback")
  static let videoMarker = localized("chat.videoMarker")
  static let videoMarkersFailed = localized("chat.videoMarkersFailed")
  static let addVideoMarker = localized("chat.addVideoMarker")
  static let playbackProgress = localized("chat.playbackProgress")
  static let playbackSpeed = localized("chat.playbackSpeed")
  static let selected = localized("chat.selected")
  static let playbackFailed = localized("chat.playbackFailed")
  static let refreshing = localized("chat.refreshing")
  static let addAttachment = localized("chat.addAttachment")
  static let back = localized("chat.back")
  static let continueSelection = localized("chat.continueSelection")
  static let continueToChat = localized("chat.continueToChat")
  static let includeVideo = localized("chat.includeVideo")
  static let invalidSetRecord = localized("chat.invalidSetRecord")
  static let messageTooLong = localized("chat.messageTooLong")
  static let noShareableSets = localized("chat.noShareableSets")
  static let noShareableSetsDescription = localized("chat.noShareableSetsDescription")
  static let loggedSetCardLabel = localized("chat.loggedSetCardLabel")
  static let plannedSetCardLabel = localized("chat.plannedSetCardLabel")
  static let rpeMetric = localized("chat.rpeMetric")
  static let removeTrainingShare = localized("chat.removeTrainingShare")
  static let sendCurrentSetRecord = localized("chat.sendCurrentSetRecord")
  static let sendCurrentSetPlan = localized("chat.sendCurrentSetPlan")
  static let setCardDelivered = localized("chat.setCardDelivered")
  static let setCardRead = localized("chat.setCardRead")
  static let setRefNotePlaceholder = localized("chat.setRefNotePlaceholder")
  static let shareTodayTraining = localized("chat.shareTodayTraining")
  static let completedSection = localized("chat.completedSection")
  static let todayPlanSection = localized("chat.todayPlanSection")
  static let trainingLoadFailed = localized("chat.trainingLoadFailed")
  static let trainingShareFailed = localized("chat.trainingShareFailed")
  static let videoFailed = localized("chat.videoFailed")
  static let videoReady = localized("chat.videoReady")
  static let videoUnavailable = localized("chat.videoUnavailable")
  static let videoUploading = localized("chat.videoUploading")
  static let weightRepsMetric = localized("chat.weightRepsMetric")

  static func videoMarkers(_ count: Int) -> String {
    localized("chat.videoMarkers").replacing("{count}", with: count.formatted())
  }

  static func seekToVideoMarker(_ time: String) -> String {
    localized("chat.seekToVideoMarker").replacing("{time}", with: time)
  }

  private static func localized(_ key: String.LocalizationValue) -> String {
    String(localized: key, bundle: .module)
  }
}
